### ISSUE TITLE
IllegalArgumentException : RoleID can't be null

### ISSUE THREAD

**Issue by czoeller** [Polarion/com.polarion.alm.extensions.codereview#1]
Hi,
I followed the instructions for step 1 but get this error:

``` java
Error in document content.
Error number 4001 in 4: Error while parsing velocity page project/drivepilot/page/_default/Code Review
Wrapped Exception: Invocation of method 'getUsersForContextRole' in  class $ISecurityService_156981577f7 threw exception class java.lang.IllegalArgumentException : RoleID can't be null
```

My configuration:

``` velocity
## --- configuration ---
set($codeReviewerRole = "project_code_reviewer")
set($awaitingCodeReviewQuery = "status:awaiting-code-review")
set($codeReviewerField = "codeReviewer")
#set($projectId = $page.space.projectId)
set($projectId = $page.getSpace().getProjectId())
## --- configuration end ---
```

(everything default except I had to change the calls to get the projectId)

I used the example project drivepilot to integrate the review extension. 
I assume the Workitem `Task` should be changed to be configured as shown in the readme: ![https://github.com/Polarion/com.polarion.alm.extensions.codereview/raw/master/docs/workflow.png](https://github.com/Polarion/com.polarion.alm.extensions.codereview/raw/master/docs/workflow.png)
I assume step 2 is optional and this error should not appear at this point.

Do you have an idea what possibly causes this error?

**Comment by srcx** [comment]
You have removed # from the front of the set lines: #set is a Velocity statement, not comment, so if you leave it be then it will start to work.

**Comment by pupca** [comment]
```
## --- configuration ---
#set($codeReviewerRole = "project_code_reviewer")
#set($awaitingCodeReviewQuery = "status:awaiting-code-review")
#set($codeReviewerField = "codeReviewer")
##set($projectId = $page.space.projectId)
#set($projectId = $page.getSpace().getProjectId())
## --- configuration end ---
```

would be the way that @srcx is describing..

**Comment by czoeller** [comment]
Sorry I'm new to velocity and wiki syntax made a wrong assumption about `#`
This fixed the error. Thank you!
